#!/bin/sh

run () {
  sudo umount mnt
  sudo rmmod jifs
  make
  sudo dd if=/dev/zero of=img bs=4096 count=100
  sudo insmod jifs.ko
  sudo mount -o loop,dbgmask=16 -t jifs img mnt
}

clean () {
  sudo umount mnt
  sudo rmmod jifs
  make clean
}

mount()
{
  sudo mount -o loop -t jifs img mnt
}

fs_test() {
  run
  echo "*** TEST START ***"
}

case "$1" in
  clean)
    clean
    ;;
  test)
    mount
    ;;
  *)
    run
    ;;
esac
exit 0
